pipeline {
    agent { docker 'maven:3.3.3' }
    stages {
        stage('test') {
            steps {
                sh 'mvn clean test'
            }
        }
        stage('build') {
            steps {
                sh 'mvn clean package spring-boot:repackage'
            }
        }
    }

    post {
        always {
            junit 'target/surefire-reports/*.xml'
        }
    }
}