pipeline {
    agent { docker 'maven:3.3.3' }
    stages {
        stage('test') {
            steps {
                sh 'mvn clean test'
            }
        }
        stage('build') {
            steps {
                sh 'mvn clean package spring-boot:repackage'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            junit 'target/surefire-reports/*.xml'
            deleteDir()
        }

        success {
            slackSend channel: '#jenkins',
                    color: 'good',
                    message: "The pipeline ${currentBuild.absoluteUrl} completed successfully.",
                    teamDomain: 'https://homenkavtur.slack.com/services/hooks/jenkins-ci/',
                    token: 'A5ty9q073w9JqwFO4aKWi13J'
        }

    }
}