version: '3.3'
services:
  front-proxy:
    image: nkavtur/front-proxy:latest
    ports:
      - 80:80
      - 9901:9901
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    configs:
      - envoy.yaml
    networks:
      - service_mesh
  service1:
    image: nkavtur/service1:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 500M
    secrets:
      - service1-application.yml
    networks:
      - service_mesh
  service2:
    image: nkavtur/service2:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 500M
    secrets:
      - service2-application.yml
    networks:
      - service_mesh
networks:
  service_mesh:
    driver: overlay
    attachable: true
configs:
  envoy.yaml:
    file: ../front-proxy/envoy/envoy-proxy.yaml
secrets:
  service1-application.yml:
    file: ../service1/src/main/resources/application.yaml
  service2-application.yml:
    file: ../service2/src/main/resources/application.yaml