version: '3'
services:
  front-proxy:
    image: front-proxy:latest
    ports:
      - 80:80
      - 9901:9901
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - service_mesh
  service1:
    image: service1:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - service_mesh
  service2:
    image: service2:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 500M
    networks:
      - service_mesh
networks:
  service_mesh :